Imports DevExpress.XtraCharts
Imports DevExpress.XtraPivotGrid
Imports DevExpress.XtraPrinting
Imports DevExpress.XtraPrintingLinks
Imports System
Imports System.Windows.Forms

Namespace WinFormsExport
	Partial Public Class Form1
		Inherits DevExpress.XtraEditors.XtraForm

		Public Sub New()
			InitializeComponent()
			Dim toolStripMenuItem1 As New ToolStripMenuItem()
			Dim toolStripMenuItem2 As New ToolStripMenuItem()
			menuStrip1.Items.AddRange(New ToolStripItem() { toolStripMenuItem1, toolStripMenuItem2 })
			toolStripMenuItem1.Name = "Print Preview"
			toolStripMenuItem1.Text = "Print Preview"
			toolStripMenuItem2.Name = "Export to XLSX"
			toolStripMenuItem2.Text = "Export to XLSX"

			AddHandler toolStripMenuItem1.Click, AddressOf toolsToolStripMenuItem2_Click
			AddHandler toolStripMenuItem2.Click, AddressOf toolsToolStripMenuItem_Click

			' This line of code is generated by Data Source Configuration Wizard
			' Fill the ExcelDataSource asynchronously
			excelDataSource1.FillAsync()
		End Sub

		Private Function CreateCompositeLink(ByVal pivotGridControl1 As PivotGridControl, ByVal chartControl1 As ChartControl) As CompositeLink
			Dim pivotLink As New PrintableComponentLink()
			pivotLink.Component = pivotGridControl1
			Dim chartLink As New PrintableComponentLink()
			chartLink.Component = chartControl1
			Dim compositeLink As New CompositeLink(New PrintingSystem())
			compositeLink.Links.AddRange(New Object() { pivotLink, chartLink })
			Return compositeLink
		End Function

		Private Sub toolsToolStripMenuItem_Click(ByVal sender As Object, ByVal e As EventArgs)
			Dim saveFileDialog1 As New SaveFileDialog()
			saveFileDialog1.Filter = "Excel Workbook|*.xlsx"
			saveFileDialog1.ShowDialog()
			If saveFileDialog1.FileName <> "" Then
				Dim compositeLink As CompositeLink = CreateCompositeLink(pivotGridControl1, chartControl1)
				compositeLink.ExportToXlsx(saveFileDialog1.FileName)
			End If
		End Sub
		Private Sub toolsToolStripMenuItem2_Click(ByVal sender As Object, ByVal e As EventArgs)
			Dim compositeLink As CompositeLink = CreateCompositeLink(pivotGridControl1, chartControl1)
			compositeLink.ShowPreview()
		End Sub

	End Class
End Namespace
